version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/car_api?connect_timeout=3000
    command: bash -c "npm install && npx prisma migrate dev && npm run start:dev"
    depends_on:
      - db
    

  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: car_api      
